# fly.toml app configuration file generated for prog on 2024-08-17T15:39:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prog'
primary_region = 'lhr'

[build]

[env]
PORT = '8080'

[[mounts]]
source = 'sqlite_data'
destination = '/data'
processes = ["app"]

[[restart]]
policy = "always"
retries = 10
processes = ["app"]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
